yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: pnp
pnpEnableEsmLoader: false
enableStrictSsl: false
httpTimeout: 300000
enableInlineBuilds: true
enableGlobalCache: false
packageExtensions:
  eslint-config-next@*:
    dependencies:
      aws-cdk-lib: '*'