name: Push to ECR

on:
  push:
    branches: [ 'main' ]
  release:
    types: [ 'published' ]

jobs:
  push-container:
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Create and Push Image"
        uses: ./.github/actions/ecr-push
        with:
          aws_account_id: ${{vars.AWS_REGION}}
          aws_region: ap-south-1
          aws_role_to_assume: gitHubSaasDeployRole
          dockerfile: packages/installer/Dockerfile
          ecr_repo_name: nsa-installer
